# This is a basic workflow that is manually triggered

name: TestPROGPOE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
       # list contents or directory
      - name: List contents
        run: ls
     # Compiles classes to test 
      - name: compile classes
        working-directory: ./src
        run: javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" ./kanban_board/Kanban_Board.java ./kanban_board/Login.java ./kanban_board/Task.java ./kanban_board/ReportHandling.java  "../test/kanban_board/Kanban_BoardTest.java"  "../test/kanban_board/LoginTest.java" "../test/kanban_board/TaskTest.java" "../test/kanban_board/ReportHandlingTest.java" 

    # list contents of src to verify that classess compiled 
      - name: List contents of src directory after compile
        working-directory: ./src/kanban_board
        run: ls
        
        
       # copy compiled classes to test directory 
      - name : copy compiled classes to testresources directory 
        working-directory: ./src/kanban_board
        run: cp -t  "../../test/kanban_board" Kanban_Board.class Login.class Task.class ReportHandling.class
        
        #copy compiled tests 
      - name : copy compiled Test classes to testresources directory 
        working-directory: ./test/kanban_board
        run: cp -t  "../../testresources/" Kanban_BoardTest.class LoginTest.class TaskTest.class ReportHandlingTest.class 
        
        # list contents or directory
      - name: List contents test package
        working-directory: ./test/kanban_board
        run: ls
        
        #run Login Class tests and output report 
      - name: run tests and create report 
        working-directory: ./test
        run: java -jar  "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class kanban_board.LoginTest

        #run Task Class tests and output report 
      - name: run tests and create report 
        working-directory: ./test
        run: java -jar  "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class kanban_board.TaskTest

        #run ReportHandling Class tests and output report 
      - name: run tests and create report 
        working-directory: ./test
        run: java -jar  "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class kanban_board.ReportHandlingTest
